# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='\u83dc\u5355\u540d')),
                ('show', models.BooleanField(default=False, help_text='\u83dc\u5355\u662f\u5426\u663e\u793a\uff0c\u9ed8\u8ba4\u6dfb\u52a0\u4e0d\u663e\u793a', verbose_name='\u662f\u5426\u663e\u793a')),
                ('url', models.CharField(default='javascript:void(0)', help_text='\u662f\u5426\u7ed9\u83dc\u5355\u8bbe\u7f6e\u4e00\u4e2aurl\u5730\u5740', max_length=300, verbose_name='\u83dc\u5355url\u5730\u5740')),
                ('priority', models.IntegerField(default=-1, help_text='\u83dc\u5355\u7684\u663e\u793a\u987a\u5e8f\uff0c\u4f18\u5148\u7ea7\u8d8a\u5927\u663e\u793a\u8d8a\u9760\u524d', verbose_name='\u663e\u793a\u4f18\u5148\u7ea7')),
                ('code', models.CharField(help_text='\u7ed9\u83dc\u5355\u8bbe\u7f6e\u4e00\u4e2a\u7f16\u53f7\uff0c\u7528\u4e8e\u6743\u9650\u63a7\u5236', max_length=100, verbose_name='\u6743\u9650\u7f16\u53f7')),
                ('parent', models.ForeignKey(blank=True, default='0', help_text='\u5982\u679c\u6dfb\u52a0\u7684\u662f\u5b50\u83dc\u5355\uff0c\u8bf7\u9009\u62e9\u7236\u83dc\u5355', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='\u7236\u7ea7\u83dc\u5355')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'verbose_name': '\u83dc\u5355',
                'verbose_name_plural': '\u83dc\u5355',
            },
        ),
    ]
