# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['priority', 'id'], 'permissions': (('index_view', '\u9996\u9875-\u6d4f\u89c8\u6743\u9650(index_view)'),), 'verbose_name': '\u83dc\u5355', 'verbose_name_plural': '\u83dc\u5355'},
        ),
        migrations.AddField(
            model_name='menu',
            name='icon_class',
            field=models.CharField(default='', help_text='\u4f7f\u7528amaze ui\u7684\u56fe\u6807\u7c7b\u540d', max_length=100, verbose_name='\u56fe\u6807\u7c7b\u540d'),
        ),
    ]
