# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20170708_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon_class',
            field=models.CharField(blank=True, default='', help_text='\u4f7f\u7528amaze ui\u7684\u56fe\u6807\u7c7b\u540d', max_length=100, verbose_name='\u56fe\u6807\u7c7b\u540d'),
        ),
    ]
