# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170708_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, default=0, help_text='\u5982\u679c\u6dfb\u52a0\u7684\u662f\u5b50\u83dc\u5355\uff0c\u8bf7\u9009\u62e9\u7236\u83dc\u5355', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='\u7236\u7ea7\u83dc\u5355'),
        ),
    ]
