# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170708_0733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['priority', 'id'], 'permissions': (('index_view', '\u9996\u9875-\u6d4f\u89c8\u6743\u9650(index_view)'), ('data_article_view', '\u957f\u6587\u7ae0-\u6d4f\u89c8\u6743\u9650(data_article_view)')), 'verbose_name': '\u83dc\u5355', 'verbose_name_plural': '\u83dc\u5355'},
        ),
    ]
