# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extend_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='icon',
            field=models.CharField(default='', max_length=200, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='name'),
        ),
    ]
